
export const batimentData = [
    {
        nomBatiment:'A',
        type:'H',
        Etages:[
            {
                idEtage:1,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                   
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    },
                    {
                        idChmbre:7,
                        dispo:0
                    },
                    {
                        idChmbre:8,
                        dispo:0
                    },
                    {
                        idChmbre:9,
                        dispo:0
                    },
                    {
                        idChmbre:10,
                        dispo:0
                    },
                    {
                        idChmbre:11,
                        dispo:0
                    },
                    {
                        idChmbre:12,
                        dispo:0
                    },
                    {
                        idChmbre:13,
                        dispo:0
                    },
                    {
                        idChmbre:14,
                        dispo:0
                    },
                    {
                        idChmbre:15,
                        dispo:0
                    },
                    {
                        idChmbre:16,
                        dispo:0
                    },
                    {
                        idChmbre:17,
                        dispo:0
                    },
                    {
                        idChmbre:18,
                        dispo:1
                    },
                    {
                        idChmbre:19,
                        dispo:0
                    },
                    {
                        idChmbre:20,
                        dispo:0
                    },
                    {
                        idChmbre:21,
                        dispo:0
                    },
                    {
                        idChmbre:22,
                        dispo:1
                    },
                    {
                        idChmbre:23,
                        dispo:0
                    },
                    {
                        idChmbre:24,
                        dispo:2
                    },
                    {
                        idChmbre:25,
                        dispo:0
                    },
                    {
                        idChmbre:26,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    },
                    {
                        idChmbre:7,
                        dispo:0
                    },
                    {
                        idChmbre:8,
                        dispo:0
                    },
                    {
                        idChmbre:9,
                        dispo:0
                    },
                    {
                        idChmbre:10,
                        dispo:0
                    },
                    {
                        idChmbre:11,
                        dispo:0
                    },
                    {
                        idChmbre:12,
                        dispo:0
                    },
                    {
                        idChmbre:13,
                        dispo:0
                    },
                    {
                        idChmbre:14,
                        dispo:0
                    },
                    {
                        idChmbre:15,
                        dispo:0
                    },
                    {
                        idChmbre:16,
                        dispo:0
                    },
                    {
                        idChmbre:17,
                        dispo:0
                    },
                    {
                        idChmbre:18,
                        dispo:1
                    },
                    {
                        idChmbre:19,
                        dispo:0
                    },
                    {
                        idChmbre:20,
                        dispo:0
                    },
                    {
                        idChmbre:21,
                        dispo:0
                    },
                    {
                        idChmbre:22,
                        dispo:1
                    },
                    {
                        idChmbre:23,
                        dispo:0
                    },
                    {
                        idChmbre:24,
                        dispo:2
                    },{
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    },
                    {
                        idChmbre:7,
                        dispo:0
                    },
                    {
                        idChmbre:8,
                        dispo:0
                    },
                    {
                        idChmbre:9,
                        dispo:0
                    },
                    {
                        idChmbre:10,
                        dispo:0
                    },
                    {
                        idChmbre:11,
                        dispo:0
                    },
                    {
                        idChmbre:12,
                        dispo:0
                    },
                    {
                        idChmbre:13,
                        dispo:0
                    },
                    {
                        idChmbre:14,
                        dispo:0
                    },
                    {
                        idChmbre:15,
                        dispo:0
                    },
                    {
                        idChmbre:16,
                        dispo:0
                    },
                    {
                        idChmbre:17,
                        dispo:0
                    },
                    {
                        idChmbre:18,
                        dispo:1
                    },
                    {
                        idChmbre:19,
                        dispo:0
                    },
                    {
                        idChmbre:20,
                        dispo:0
                    },
                    {
                        idChmbre:21,
                        dispo:0
                    },
                    {
                        idChmbre:22,
                        dispo:1
                    },
                    {
                        idChmbre:23,
                        dispo:0
                    },
                    {
                        idChmbre:24,
                        dispo:2
                    },{
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    },
                    {
                        idChmbre:7,
                        dispo:0
                    },
                    {
                        idChmbre:8,
                        dispo:0
                    },
                    {
                        idChmbre:9,
                        dispo:0
                    },
                    {
                        idChmbre:10,
                        dispo:0
                    },
                    {
                        idChmbre:11,
                        dispo:0
                    },
                    {
                        idChmbre:12,
                        dispo:0
                    },
                    {
                        idChmbre:13,
                        dispo:0
                    },
                    {
                        idChmbre:14,
                        dispo:0
                    },
                    {
                        idChmbre:15,
                        dispo:0
                    },
                    {
                        idChmbre:16,
                        dispo:0
                    },
                    {
                        idChmbre:17,
                        dispo:0
                    },
                    {
                        idChmbre:18,
                        dispo:1
                    },
                    {
                        idChmbre:19,
                        dispo:0
                    },
                    {
                        idChmbre:20,
                        dispo:0
                    },
                    {
                        idChmbre:21,
                        dispo:0
                    },
                    {
                        idChmbre:22,
                        dispo:1
                    },
                    {
                        idChmbre:23,
                        dispo:0
                    },
                    {
                        idChmbre:24,
                        dispo:2
                    }
                ]
            },
            {
                idEtage:2,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            },         
            {
                idEtage:3,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            }
        ]
    },
    {
        nomBatiment:'B',
        type:'H',
        Etages:[
            {
                idEtage:1,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            },
            {
                idEtage:2,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            },         
            {
                idEtage:3,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            }
        ]
    },
    {
        nomBatiment:'C',
        type:'F',
        Etages:[
            {
                idEtage:1,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            },
            {
                idEtage:2,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            },         
            {
                idEtage:3,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            }
        ]
    },
    {
        nomBatiment:'TITANIC',
        type:'F',
        Etages:[
            {
                idEtage:1,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            },
            {
                idEtage:2,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            },         
            {
                idEtage:3,
                chambres:[
                    {
                        idChmbre:1,
                        dispo:0
                    },
                    {
                        idChmbre:2,
                        dispo:0
                    },
                    {
                        idChmbre:3,
                        dispo:0
                    },
                    {
                        idChmbre:4,
                        dispo:0
                    },
                    {
                        idChmbre:5,
                        dispo:0
                    },
                    {
                        idChmbre:6,
                        dispo:0
                    }
                ]
            }
        ]
    }
  ];
  
  export default batimentData; 